# Generated by Django 4.1 on 2022-08-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='owener',
            new_name='owner',
        ),
    ]
